### ISSUE TITLE
Summuning/Invasion dont work

### ISSUE THREAD

**Issue by Jeyyu** [TLeonardUK/ds3os#1]
## Mention: Tried on local Lan with Goldberg Steam emulator (to avoid ban mainly) _so this issue does maybe not occur to the original steam client._

Summon(white soap) sign can be seen but as soon as I summon someone the game crashes on both sides.

Invasion (tested with cracked eye orb) is finding one potential target but never connects.

Everything else seems to work fine.

### Just wanna say a big thank you for your effort and time. 

With a usable private server many new things will be made possible to the community, me and a lot of other people appreciate this.

![Screenshot (72)](https://user-images.githubusercontent.com/60408111/131019154-fea2e51d-d572-4492-a50c-2cbd145313ce.png)

**Edit:**

Tried with:

--> latest main commit (ed7836822796cb8bb2a28ac229ee6d8af563b300)

--> Invasions are now working! commit (cd89355febacf82f375591e2d2671240a8385e89)

-->Summon signs now work, abit a little janky right now. commit (33a3b89c08f25012ddf783ea5cd12a85735270fc)
          
        **on Summon sign commit , accepting summon sign did not crash the game, but summoning still dont work**

**Comment by TLeonardUK** [comment]
Try a more recent build, I've fixed various issues with the reliable udp stream, might fix it.

Never tried the Goldberg Steam emulator, no idea how that differs from stream, I would imagine hopefully not very. I'll try it when I get a moment. I currently mainly just test on a few family share accounts on 2 LAN pc's.

**Comment by Jeyyu** [comment]
Hey,

I tried latest commit (622041e0301d8fd0ae734c5d8123760cb18ea963) still don't work console output is in screenshot.

Yea AFAIK the emu seems to be emulation pretty much perfect.

I am building like your instructed, visual studio with vcpkg global installed/activated. 
Only thing I did was to build the Loader with dotnet build/publish command.

**If i can help anyhow I am pleased to do so, but don't expect much programming help I am still on a beginner level.**

![Screenshot (77)](https://user-images.githubusercontent.com/60408111/131233639-53bc5572-616f-4840-8ace-d8352ef00fe1.png)

**Comment by Jeyyu** [comment]
### Solution:

I transferred some generated steam interface(.txt file) stuff over a ftp server which seems to destroy the txt format in some way. 

Summoning works now as indented but invasion (tested with cracked eye orb) don't  seem work. 
**This time tested with emulator and with official steam client.**
